spring:
  application:
    name: onboarding
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: onboard
      auto-index-creation: true


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

aws:
  region: us-east-1
  access:
    key: access-key
    secret-key: secret-key
  s3:
    bucket-name: rayef-invoices
  sqs:
    queue:
      url: "https://sqs.us-east-1.amazonaws.com/241533117399/invoices"

processing:
  batch:
    size: 30

invoice:
  filename-pattern: "invoice_\\d{8}\\.csv"

cache:
  TTL: 30
  max-size: 1000

async:
  invoice:
    name: InvoiceAsync
    core-pool-size: 2
    max-pool-size: 2
    queue-capacity: 100



